//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vodpoints.edmx
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class manager
    {
        public long Id { get; set; }
        [Required]
        [StringLength(50, ErrorMessage = "超過欄位長度")]
        public string Name { get; set; }
        [StringLength(50, ErrorMessage = "超過欄位長度")]
        public string Account { get; set; }
        [StringLength(50, ErrorMessage = "超過欄位長度")]
        public string Email { get; set; }
        public string Telephone { get; set; }
        [Required(ErrorMessage = "*")]
        [DataType(DataType.Password)]
        [StringLength(50, ErrorMessage = "超過欄位長度")]
        public string Password { get; set; }
        [NotMapped]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
    }
}
