//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vodpoints.edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vodpointsdbEntities : DbContext
    {
        public vodpointsdbEntities()
            : base("name=vodpointsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<edgeserver> edgeservers { get; set; }
        public DbSet<manager> managers { get; set; }
        public DbSet<operationlog> operationlogs { get; set; }
        public DbSet<accesscontrolchildren> accesscontrolchildrens { get; set; }
        public DbSet<accesscontrolparent> accesscontrolparents { get; set; }
        public DbSet<authoritygroup> authoritygroups { get; set; }
        public DbSet<managerauthoritygroup> managerauthoritygroups { get; set; }
        public DbSet<manageraccesscontrolchildren> manageraccesscontrolchildrens { get; set; }
    }
}
